autowarefoundation/autoware_tools

- driving_environment_analyzer/CMakeLists.txt
- driving_environment_analyzer/README.md
- driving_environment_analyzer/include/driving_environment_analyzer/node.hpp
- driving_environment_analyzer/launch/driving_environment_analyzer.launch.xml
- driving_environment_analyzer/package.xml
- driving_environment_analyzer/src/node.cpp
Add `driving_environment_analyzer` tool.
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/6496
Test with ROSBAG.
```
[component_container-1] [INFO 1708999777.768870564] [driving_environment_analyzer]: ======================================
[component_container-1] [INFO 1708999777.768922452] [driving_environment_analyzer]:  data is ready. start ODD analysis... 
[component_container-1] [INFO 1708999777.768933574] [driving_environment_analyzer]: ======================================
[component_container-1] [INFO 1708999777.768967412] [driving_environment_analyzer]: - Length of total lanes : 2357.50 [m]
[component_container-1] [INFO 1708999777.769031174] [driving_environment_analyzer]: - Length of lane that has adjacent lane : 2080.43 [m]
[component_container-1] [INFO …
```
> feat(driving_environment_analyzer): add new package

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
fix dying when no  traffic signals
before
```
$ ros2 run planning_debug_tools perception_replayer.py -b Pn_UCv2.0_Pedestrian_Tracking/result_bag_0.db3
Stared loading rosbag
[INFO 1710178110.720895793] [rosbag2_storage]: Opened database 'Pn_UCv2.0_Pedestrian_Tracking/result_bag_0.db3' for READ_ONLY. (open() at ./src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.cpp:227)
Ended loading rosbag
Start timer callback
Traceback (most recent call last):
File "/home/kosuke55/pilot-auto.latest/install/planning_debug_tools/lib/planning_debug_tools/perception_replayer.py", line 198, in <module>
rclpy.spin_once(node, timeout_sec=0.01)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 202, in spin_once
executor.spin_once(timeout_sec=timeout_sec)
File …
```
> fix(perception_replyer): fix dying when no traffic signals

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/time_manager_widget.py
Add a button to the `perception_replayer` to publish the goal pose (taken from the last recorded ego pose).
Psim.
> feat(perception_replayer): add a button to publish the goal pose

- control/control_debug_tools/CMakeLists.txt
- control/control_debug_tools/package.xml
- control/control_debug_tools/scripts/consistency_checker.py
A mismatch of the parameters between the controllers and the dynamics may cause failing to stabilize the ego.
Therefore, this ticket creates a controller-dynamics consistency checker.
It checks the following parameters:
input_delay
vehicle_model_steer_tau
acceleration_limit
steer_rate_lim_dps_list_by_curvature
steer_rate_lim_dps_list_by_velocity
max_acc
min_acc
accelerate_delay
https://tier4.atlassian.net/jira/software/c/projects/RT1/boards/438?selectedIssue=RT1-5682 …
> feat(control_debug_tools): controller-dynamics consistency checker created.

- control/control_debug_tools/CMakeLists.txt
CMakeLists.txt for control_debug_tools is missing `ament_auto_package()` which produces the following warning message after build&sourcing the workspace:
```
not found: "/home/mitsudome-r/autoware/install/control_debug_tools/share/control_debug_tools/local_setup.bash"
```
This PR will make sure that package is installed to the install directory.
1. clone Autoware
2. `vcs import` autoware.repos and tools.repos 
3.  build the workspace `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release`. 
4. Run `source install/setup.bash`
N/A
N/A
After all checkboxes are checked, …
> fix(control_debug_tools): add ament_auto_package to CMakeLists.txt

- bag2lanelet/scripts/bag2map.py
- common/tier4_control_rviz_plugin/README.md
- common/tier4_control_rviz_plugin/package.xml
- common/tier4_control_rviz_plugin/src/tools/manual_controller.cpp
- common/tier4_control_rviz_plugin/src/tools/manual_controller.hpp
- driving_environment_analyzer/include/driving_environment_analyzer/analyzer_core.hpp
- driving_environment_analyzer/include/driving_environment_analyzer/driving_environment_analyzer_node.hpp
- driving_environment_analyzer/include/driving_environment_analyzer/driving_environment_analyzer_rviz_plugin.hpp
- driving_environment_analyzer/include/driving_environment_analyzer/type_alias.hpp
- driving_environment_analyzer/src/analyzer_core.cpp
- driving_environment_analyzer/src/driving_environment_analyzer_node.cpp
- driving_environment_analyzer/src/driving_environment_analyzer_rviz_plugin.cpp
- planning/planning_debug_tools/scripts/closest_velocity_checker.py
- simulator/simulator_compatibility_test/README.md
- simulator/simulator_compatibility_test/simulator_compatibility_test/publishers/ackermann_control_command.py
Fix for autoware_msgs branch
Did build check and tested that planning_simulator works without an error.
> feat: port remaining autoware_auto_msgs to autoware_msgs 

- driving_environment_analyzer/package.xml
Removes unnecessary dependency to autoware_auto_tf2.
This must be merged before https://github.com/autowarefoundation/autoware.universe/pull/7218
I have done build check with [remove-autoware-auto-tf2](https://github.com/mitsudome-r/autoware.universe/tree/remove-autoware-auto-tf2) branch on my local machine
None
None
None …
> feat(driving_environment_analyzer): remove dependency to autoware_auto_tf2

- bag2lanelet/scripts/bag2map.py
- driving_environment_analyzer/package.xml
Fixes for adding the autoware_ prefix
* https://github.com/autowarefoundation/autoware.universe/pull/7288
before
```
~/autoware$ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
driving_environment_analyzer: Cannot locate rosdep definition for [behavior_path_planner_common]
```
after
```
~/autoware$ rosdep install -y --from-paths src --ignore-src --rosdistro humble
#All required rosdeps installed successfully
```
After all checkboxes are checked, anyone who has …
> fix(driving_environment_analyzer): fixed depend pkg name about behavior_path_planner_common

- driving_environment_analyzer/include/driving_environment_analyzer/analyzer_core.hpp
- driving_environment_analyzer/include/driving_environment_analyzer/type_alias.hpp
- driving_environment_analyzer/include/driving_environment_analyzer/utils.hpp
- driving_environment_analyzer/package.xml
- driving_environment_analyzer/src/utils.cpp
Fixes for adding autoware_ prefix to route handler
- https://github.com/autowarefoundation/autoware.universe/pull/7341
Should be merged after linked PR is closed.
> fix(driving_environment_analyzer): fix dependency and code related to route_handler

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
Fix a bug that perception_replayer/perception_reproducer can't publish old 'autoware_auto_perception_msgs' in old rosbags, by converting old `autoware_auto_perception_msgs` messages to `autoware_perception_msgs` messages 
> fix(perception_reproducer): support reproduce/replay old rosbags

- localization/deviation_estimation_tools/deviation_estimator/src/deviation_estimator_main.cpp
Fixed an issue where an error would occur when executing a rosbag with imu before /tf_static arrived, causing a non-existent frame_id to be specified in the transform lookup.
The below command works fine:
```bash
~/autoware/install/deviation_estimator/lib/deviation_estimator/deviation_estimator_unit_tool <rosbag_path>
``` …
> fix(deviation_estimator): fix lookup error before subscribe /tf_static

- .github/workflows/build-and-test-differential-self-hosted.yaml
- .github/workflows/build-and-test-differential.yaml
Similar to:
https://github.com/autowarefoundation/autoware.universe/blob/82a10de1f7b49eeeb80108ea3aa6a477d79220f5/.github/workflows/build-and-test-differential.yaml#L39-L46
It will fetch the PR commits for the modified files workflow to function.
For mor details, see:
* https://github.com/autowarefoundation/autoware-github-actions/blob/92b81882b5e5a67da07211aa997f61f7d9f94be7/get-modified-packages/README.md#fetch-only-the-pr-branch-and-all-pr-commits
Fixes:
- https://github.com/autowarefoundation/autoware_tools/actions/runs/9552231579/job/26328319273?pr=54#step:6:21
[It passes.](https://github.com/autowarefoundation/autoware_tools/actions/runs/9553341476/job/26331951966?pr=55#step:7:35) 
This is not a good test since this is only a single commit and there are no modified packages.
But …
> ci(build-and-test-differential): fix fetch depth

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
add logger configuration for behavior path planner dynamic obstacle avoidance
change logger level in rviz panel
output debug level log in the terminal
> feat(tier4_logging_level_configure_rviz_plugin): update logger configuration for behavior path planner dynamic obstacle avoidance

- common/tier4_debug_tools/include/tier4_debug_tools/lateral_error_publisher.hpp
- common/tier4_debug_tools/package.xml
- common/tier4_debug_tools/src/lateral_error_publisher.cpp
- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
- driving_environment_analyzer/package.xml
- driving_environment_analyzer/src/utils.cpp
- planning/planning_debug_tools/include/planning_debug_tools/trajectory_analyzer.hpp
- planning/planning_debug_tools/include/planning_debug_tools/util.hpp
- planning/planning_debug_tools/package.xml
https://github.com/orgs/autowarefoundation/discussions/4881
https://github.com/autowarefoundation/autoware.universe/pull/7539
evaluator
https://evaluation.tier4.jp/evaluation/reports/5108f1ef-8656-58ba-96ae-1d831a471aaf?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/ffdd4991-3143-5338-b1e9-df6ba9903331?project_id=prd_jt …
> refactor(motion_utils)!: add autoware prefix and include dir

- localization/deviation_estimation_tools/deviation_estimator/package.xml
- localization/deviation_estimation_tools/deviation_evaluator/package.xml
There is no codeowner of deviation_estimation_tools in TIER IV Localization & Mapping team. So I would like to add some members to it.
Nothing
Nothing
Nothing
Nothing
Nothing
> chore: update codeowners on deviation_estimation_tools

- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
change the default reproduce-cool-down to 80s, improved the perception reproducer in case of long-term stop.
An example rosbag at the intersection. (https://tier4.atlassian.net/browse/RT1-5797)
[Screencast from 2024年06月19日 16時47分45秒.webm](https://github.com/autowarefoundation/autoware_tools/assets/24828656/874be271-7a25-40f2-bc86-ba1acb394b54) …
> fix: change_perception_reproducer_parameter

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
> fix(percerption_replayer): make sure that old message in rosbags can be converted to new type correctly

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
Previous [PR](https://github.com/autowarefoundation/autoware.universe/pull/7168) changed the module name as
`behavior_path_avoidance_module -> autoware_behavior_path_static_obstacle_avoidance_module`,
Changed the logger name to static_obstacle_avoidance.
[PR](https://github.com/autowarefoundation/autoware.universe/pull/7617)
PSim
None …
> fix(logging_level_configure): change to static_obstacle_avoidance from avoidance

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
In the previous [PR](https://github.com/autowarefoundation/autoware_tools/pull/60), I incorrectly assumed that the code for converting old messages was wrong. 
But in fact, there are two old messages with the same name`TrafficSignalArray`, so this PR aim to support both old messages.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-gui …
> fix(perception_replayer): support two kinds of old messages in rosbags

- evaluation/tier4_metrics_rviz_plugin/CMakeLists.txt
- evaluation/tier4_metrics_rviz_plugin/config/metrics_visualize_panel.param.yaml
- evaluation/tier4_metrics_rviz_plugin/include/metrics_visualize_panel.hpp
- evaluation/tier4_metrics_rviz_plugin/package.xml
- evaluation/tier4_metrics_rviz_plugin/src/metrics_visualize_panel.cpp
Example
```yaml
curvature:
table: true
graph: false
point_interval:
table: true
graph: false
length:
table: true
graph: false
duration:
table: false
graph: true
velocity:
table: true
graph: false
acceleration:
table: true
graph: false
jerk:
table: true
graph: true
lateral_deviation:
table: true
graph: true
yaw_deviation:
table: true
graph: false
velocity_deviation:
table: true
graph: false
stability:
table: true
graph: false
stability_frechet:
table: true
graph: false
obstacle_distance:
table: true
graph: false
obstacle_ttc:
table: true
graph: false
modified_goal_longitudinal_deviation:
table: false
graph: false
modified_goal_lateral_deviation:
table: false
graph: false
modified_goal_yaw_deviation:
table: false
graph: false
```
The PR author **must** check the checkboxes below when …
> feat(metrics_visualize_panel): make it possible to hide graph for each metrics

- planning/autoware_route_client/CMakeLists.txt
- planning/autoware_route_client/README.md
- planning/autoware_route_client/package.xml
- planning/autoware_route_client/scripts/route_client.py
Add `autoware_route_client` package.
https://github.com/autowarefoundation/autoware_tools/assets/10190493/5070920c-97a4-4a57-914f-2949eb6ffe34
Not applicable.
Not applicable.
> feat(autoware_route_client): add autoware_route_client package

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
Implement some improvements in perception reproducer:
1. [improve] Refactored code to make it easier to read.
2. [improve] Now, the reproduce sequence is generated only when the moved distance of ego is larger than `search_radius`, greatly reducing the time of sequence generation. It can speed up the process especially when there are a lot of objects.
3. [feat] Add noises to perceived objects when repeatedly publishing the same messages.
[Screencast from 2024年07月10日 17時26分05秒.webm](https://github.com/autowarefoundation/autoware_tools/assets/24828656/26dc0167-e9a4-4bb6-b150-a8a8e235171a)
5. [feat] Add a constraint to avoid publishing too fast when there is a speed gap between the ego and the rosbag's ego when the ego is departing/stopping while the rosbag's ego is moving. [related …
> feat(perception reproducer): some improvements in perception reproducer.

- common/tier4_automatic_goal_rviz_plugin/src/automatic_goal_sender.cpp
- common/tier4_automatic_goal_rviz_plugin/src/automatic_goal_sender.hpp
The current automatic_goal_sender is set to call the ```/api/operation_mode/change_to_autonomous``` service as soon as ```/api/routing/state``` becomes ```RouteState::SET```. However, in this state, Planning may still be in preparation, and autonomous_mode may not be ready. In such situations, the automatic_goal_sender process crashes as shown in the message below. I have modified the code to wait for autonomous_mode to be ready before calling the change_to_autonomous service.
```
automatic_goal_sender-1] [INFO 1720670631.443807582] [automatic_goal_sender]: Achieved goals will be saved in: /home/kimura/git/pilot-auto.x2/src/evaluation/autoware_awsim_evaluation_tools/src/awsim_evaluation_launcher/config/odaibagoals_achieved.log
[automatic_goal_sender-1] [INFO 1720670632.443782270] …
```
> feat: wait until autonomous mode is enabled

- control_data_collecting_tool/README.md
- control_data_collecting_tool/scripts/data_collecting_pure_pursuit_trajectory_follower.py
- control_data_collecting_tool/scripts/data_collecting_trajectory_publisher.py
- Smoothed the lateral acceleration constraint
- bug fix: small modification https://github.com/autowarefoundation/autoware_tools/commit/abaebea214046e0067f1ef6ffa850a57a013d792
----
This PR is same to #78. This is a PR that has been reissued to avoid git conflicts. 
#78 should be closed without merge.
> feat(control_data_collecting_tool): smoothing and bug fix

- localization/deviation_estimation_tools/deviation_evaluator/launch/deviation_evaluator.launch.xml
- vehicle/parameter_estimator/launch/parameter_estimator_with_simulation.launch.xml
The following pull request changed map.launch.py to map.launch.xml.
* https://github.com/autowarefoundation/autoware.universe/pull/6185
This pull request will follow up on that change.
I have only tested the operation of the deviation_evaluator. However, as I have never run the previous version, I do not know whether it is operating correctly or not.
No operation checks have been carried out for parameter_estimator.
None.
None. …
> fix: changed map.launch file from .py to .xml

- control_data_collecting_tool/package.xml
- control_data_collecting_tool/scripts/data_collecting_trajectory_publisher.py
visualize collected acc and vel grid
https://github.com/user-attachments/assets/78ba2601-9884-4670-ae0b-c3374ce6a840
psim
> feat(data_collecting_tool): visualize collected acc and vel grid

- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/node.py
- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/print_tree.py
- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/tree.py
If 'r' is clicked, json which written in below is copied to clipboard.
```json
[
{
"name": "onPath",
"processing_time": 107.498,
"comment": "",
"children": [
{
"name": "generateOptimizedTrajectory",
"processing_time": 106.253,
"comment": "",
"children": [
{
"name": "optimizeTrajectory",
"processing_time": 69.672,
"comment": "",
"children": [
{
"name": "optimizeTrajectory",
"processing_time": 69.658,
"comment": "",
"children": [
{
"name": "calcReferencePoints",
"processing_time": 18.417,
"comment": "",
"children": [
{
"name": "resampleReferencePoints",
"processing_time": 1.576,
"comment": "",
"children": []
},
{
"name": "updateFixedPoint",
"processing_time": 1.534,
"comment": "",
"children": []
},
{
"name": "updateBounds",
"processing_time": 1.256,
"comment": "",
"children": []
},
{ …
```
> feat(autoware_dubug_tools): add function to report worst time when r is pressed at the end

- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/node.py
Current `processing_time_visualizer` need interactive input which is not good to use in scripts.
This PR add 
- topic choice with node argument with prefix `-t`
Sample usage
```
ros2 run autoware_debug_tools processing_time_visualizer -t /perception/object_recognition/prediction/map_based_prediction/debug/processing_time_detail_ms
``` …
> feat(processing_time_visualizer): enable to give topic by command arg

- localization/deviation_estimation_tools/deviation_estimator/package.xml
In the issue (https://github.com/autowarefoundation/autoware/issues/5089), missing depends were found.
This pull request adds those depends to `deviation_estimator`.
When adding the `rosbag2_storage_mcap` pkg as `<depend>`, the following error occurred. So I add the pkg as `<exec_depend>`.
```
CMake Error in CMakeLists.txt:
Imported target "rosbag2_storage_mcap::rosbag2_storage_mcap" includes
non-existent path
"/opt/ros/humble/include/rosbag2_storage_mcap"
in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
* The path was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and references files it does not
provide.
``` …
> fix(deviation_estimator): add depend

- planning/autoware_route_client/scripts/route_client.py
currently client always print 
```
[route_client]: Service requested.
```
when getting result regardless of it's status.
In this PR, print status too.
```
$ ros2 run autoware_route_client route_client.py  /home/kosuke55/Downloads/route4.txt
[INFO 1723808387.338352599] [route_client]: Service failed: Cannot reroute as the planner is not in lane following. (main() at /home/kosuke55/pilot-auto/install/autoware_route_client/lib/autoware_route_client/route_client.py:103)
```
psim …
> feat(route_client): print result

- control/control_debug_tools/scripts/lateral_deviation_monitor.py
python3 lateral_deviation_monitor.py
https://github.com/user-attachments/assets/3abb450d-c764-4b82-b72b-5b754d594f94
psim
> feat(control): add lateral deviation monitor

- evaluation/tier4_metrics_rviz_plugin/include/metrics_visualize_panel.hpp
`tier4_rviz_metrics_plugin` dies when metrics value includes string values. I fixed the tool so that it can skip process for such kind of metric. (e.g. KEY:decision VALUE:deceleration)
> fix(metrics): fix std::stod exception

- evaluation/tier4_metrics_rviz_plugin/README.md
This PR fix that topic name changes made by https://github.com/autowarefoundation/autoware_tools/pull/82 were not reflected in README.md.
> chore: fix topic name in README.md

- system/rqt_diagnostic_graph_monitor/python/module.py
Fix following error.
```
File "/home/user/autoware/install/rqt_diagnostic_graph_monitor/local/lib/python3.10/dist-packages/rqt_diagnostic_graph_monitor/module.py", line 46, in on_status
self.graph.update(msg)
AttributeError: 'NoneType' object has no attribute 'update'
```
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/CTEJP8L4T/p1724807383750299?thread_ts=1719556079.188599&cid=CTEJP8L4T)
Publish diag graph status before struct.
Terminal1: `ros2 run rqt_diagnostic_graph_monitor rqt_diagnostic_graph_monitor`
Terminal2: `ros2 topic pub /diagnostics_graph/status tier4_system_msgs/msg/DiagGraphStatus`
None
None
None
The PR author **must** check …
> feat(rqt_diagnostic_graph_monitor): ignore status before struct

- driving_environment_analyzer/launch/driving_environment_analyzer.launch.xml
This PR will add `autoware_` prefix to `map_projection_loader`
Reflect the change of https://github.com/autowarefoundation/autoware.universe/pull/8420
> fix(map_projection_loader): add autoware prefix to map_projection_loader

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
- planning/planning_debug_tools/README.md
- planning/planning_debug_tools/launch/trajectory_analyzer.launch.xml
- planning/planning_debug_tools/scripts/closest_velocity_checker.py
- planning/planning_debug_tools/scripts/trajectory_visualizer.py
- planning/planning_debug_tools/scripts/update_logger_level.sh
obstacle_avoidance_planner -> path_optimizer
related to:
https://github.com/orgs/autowarefoundation/discussions/4741
fix some tools to work
> refactor(path_optimizer): rename package name and fix trajectory visualizer

- build_depends.repos
- planning/planning_debug_tools/package.xml
perception reproducer uses `autoware_perception_msgs` and `autoware_auto_perception_msgs` to load and analyze rosbags, so add the packages to the dependency.
> chore: add percpetion msgs to dependance

- build_depends.repos
- map/autoware_lanelet2_map_utils/CMakeLists.txt
- map/autoware_lanelet2_map_utils/README.md
- map/autoware_lanelet2_map_utils/config/fix_z_value_by_pcd.param.yaml
- map/autoware_lanelet2_map_utils/config/transform_maps.param.yaml
- map/autoware_lanelet2_map_utils/launch/fix_z_value_by_pcd.launch.xml
- map/autoware_lanelet2_map_utils/launch/transform_maps.launch.xml
- map/autoware_lanelet2_map_utils/package.xml
- map/autoware_lanelet2_map_utils/schema/transform_maps.schema.json
- map/autoware_lanelet2_map_utils/src/fix_lane_change_tags.cpp
- map/autoware_lanelet2_map_utils/src/fix_z_value_by_pcd.cpp
- map/autoware_lanelet2_map_utils/src/merge_close_lines.cpp
- map/autoware_lanelet2_map_utils/src/merge_close_points.cpp
- map/autoware_lanelet2_map_utils/src/remove_unreferenced_geometry.cpp
- map/autoware_lanelet2_map_utils/src/transform_maps.cpp
This PR will add `map/autoware_lanelet2_map_utils` which is a port of [`autoware.universe/map/util/lanelet2_map_preprocessor`](https://github.com/autowarefoundation/autoware.universe/tree/main/map/util/lanelet2_map_preprocessor) .
After this PR, the `lanelet2_map_preprocessor` in the autoware.universe  will be get removed and only the link to this package remains.
Changes
- add `autoware_lanelet2_map_utils`
- add dependency `autoware_lanelet2_extension` to `build_depends.repo` …
> feat(map): port lanelet2_map_preprocessor from autoware.universe

- map/autoware_pointcloud_merger/src/pcd_merger.cpp
- In autoware_pointcloud_merger, when a downsampling resolution is specified, the autoware_pointcloud_divider is used to downsample the input PCD files. The downsampled files are stored in a directory named _pointcloud_merger_tmp/pointcloud_map.pcd_. After that, the pointcloud merger iterates on the segmented files and merge them to a single output PCD file. However, the merger only uses a filesystem::directory_iterator to iterate on the _pointcloud_merger_tmp_ directory, so it will not be able to detect any PCD files because they are put under the pointcloud_map.pcd directory. This PR replaces directory_iterator by recursive_directory_iterator, thus fixes that problem.
None
- Merged with downsampling resolution 0.2.
None
None
None
The PR author **must** check the checkboxes below when …
> fix: fixed a bug from autoware pointcloud merger

- map/autoware_pointcloud_divider/include/autoware/pointcloud_divider/pcd_io_reader.hpp
- Fix a bug in the customized pcd reader, which reads more points from a pcd file than the reader should do. Basically, the number of points stored in a PCD file is stated at the header of the file. However, a PCD file may contains some extra bytes of unknown data (like the one generated by CloudCompare). This PR enables the pcd reader to stop loading points after the number of loaded points equal to the number of points specified in the header of the file.
None
- [Input data](https://drive.google.com/file/d/1s5RvbBjgBtLWaGh8iDI5ApOv0cizEHdE/view?usp=drive_link)
- When run pointcloud divider on the input data, the old code generates a segment named `prefix_0_0.pcd`. This file is generated from the extra bytes at the end of the input PCD file. This is not correct. When using the new code, …
> fix(autoware_pointcloud_divider): fix a bug in the customized pcd reader

- common/rtc_manager_rviz_plugin/src/rtc_manager_panel.cpp
- common/rtc_manager_rviz_plugin/src/rtc_manager_panel.hpp
The RTC status could be observed by the RTCManagerPanel in Rviz.
Currently the cooperateStatus/[State](https://github.com/tier4/tier4_autoware_msgs/blob/tier4/universe/tier4_rtc_msgs/msg/State.msg) could not be observed by the panel.
In this PR, I have added a column named "State" to observe the state transition of the cooperateStatus/state.
None
PSim
None
None
None …
> feat(rtc_manager_panel): add cooperateStatus state column

- localization/deviation_estimation_tools/deviation_evaluator/launch/deviation_evaluator.launch.xml
This PR will add the `autoware_` prefix to `ekf_localizer`.
Also added `autoware_` prefix to `gyro_odometer` which was not update for the case of `autoware_gyro_odometer` update.
Reflect the change of https://github.com/autowarefoundation/autoware.universe/pull/8888
https://github.com/autowarefoundation/autoware.universe/pull/8888 …
> fix(ekf_localizer): add autoware prefix to ekf_localizer

- control/stop_accel_evaluator/include/stop_accel_evaluator/stop_accel_evaluator_node.hpp
- control/stop_accel_evaluator/package.xml
- driving_environment_analyzer/package.xml
This PR updates the packages that depend on `signal_processing` to now depend on `autoware_signal_processing`
https://github.com/autowarefoundation/autoware.universe/pull/8541
> refactor: update signal_processing downstream dependencies

- driving_environment_analyzer/package.xml
Follow up from:
- https://github.com/autowarefoundation/autoware.universe/pull/8088
There is no mention of the word "interpolation" within this package directory. I have doubts that this package uses this dependency.
:rotating_light: :warning: Must be merged after:
- https://github.com/autowarefoundation/autoware.universe/pull/8088 …
> fix(driving_environment_analyzer): remove unused autoware_interpolation dependency

- common/tier4_control_rviz_plugin/src/tools/manual_controller.cpp
Currently the control_rviz_plugin cannot be activated once the vehicle has changed its gear to PARKING, as the following output occurs.
```
1727785737.7806146 [component_container_mt-39] [[INFO 1727785737.779172848] [control.vehicle_cmd_gate]: The operation mode is changed, but the GearCommand is not received yet: (getContinuousTopic():368)
```
This is because no value is assigned to timestamp to the gear_cmd.
The above problem would be fixed in this PR.
None
PSim
Before:
[Screencast from 2024年10月01日 21時28分35秒.webm](https://github.com/user-attachments/assets/aa6b75af-eb87-44e9-9e51-c702f7bc8fab)
After:
[Screencast from 2024年10月01日 21時35分58秒.webm](https://github.com/user-attachments/assets/262cebc5-d12c-4ddb-9eaf-09573ba1395e)
The warning have nothing to do with the gear command as it is …
> feat(tier4_control_rviz_plugin): add timestamp to gear command

- common/tier4_screen_capture_rviz_plugin/CMakeLists.txt
- common/tier4_screen_capture_rviz_plugin/package.xml
- common/tier4_screen_capture_rviz_plugin/plugins/plugin_description.xml
- common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.cpp
- common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.hpp
- common/tier4_screen_capture_rviz_plugin/srv/Capture.srv
I added new srv type to capture screen shot or movie by external trigger.
```
uint8 SCREEN_SHOT = 0
uint8 START_BUFFERING = 1
uint8 STOP_BUFFERING = 2
uint8 RECORD = 3
uint8 SAVE = 4
uint8 SAVE_BUFFER = 5
uint8 action
string file_name
---
bool success
```
```
ros2 service call /debug/capture tier4_screen_capture_rviz_plugin/srv/Capture "{action: 0, file_name: "test"}"
```
https://github.com/user-attachments/assets/95848bc1-d340-4ae6-88a8-84e1be767ad8
start recording
```
ros2 service call /debug/capture tier4_screen_capture_rviz_plugin/srv/Capture "{action: 3, file_name: ""}"
```
save
```
ros2 service call /debug/capture tier4_screen_capture_rviz_plugin/srv/Capture "{action: 4, file_name: "test-2"}"
```
https://github.com/user-attachments/assets/5b5ddda0-d37d-4cb6-ad37-0bd2e625d311
start …
> feat: use new srv to capture screen shot and movie

- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
When the psim-ego stops in front of a red traffic light and the rosbag-ego moves at a distance from the psim-ego, the reproducer stops publishing new messages so that the psim-ego freezes forever (because the traffic lights keep red forever). 
This is a cherry-pick of https://github.com/tier4/autoware.universe/pull/1578
**Parent Issue:**
- Link
Test with Psim:
(The purple trajectory is rosbag-ego.)
Before:
[Screencast from 10-04-2024 06:39:20 PM.webm](https://github.com/user-attachments/assets/f48e9967-e80e-46a2-871a-9472ed84109e)
After:
[Screencast from 10-04-2024 06:38:00 PM.webm](https://github.com/user-attachments/assets/b3457af6-44f7-42b8-ac19-e84868c01d7c)
None.
None.
None.
> fix(planning_debug_tools): fix a bug of perception reproducer

- common/autoware_debug_tools/autoware_debug_tools/system_performance_plotter/system_performance_plotter_base.py
`system_performance_plotter` is useful, but there is an issue that `plt.show()` is executed when plotting a graph, and the plot will not proceed unless the screen is closed each time.
This pull request will fix that.
It will continue to work as before unless it is run with `-p` or `--skip_plot_show`.
If you have any better suggestions please let me know.
I have confirmed that `system_performance_plotter` works well.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
> feat: add "skip_plt_show" arg to plotter

- common/autoware_debug_tools/autoware_debug_tools/system_usage_monitor.py
This PR changes the node search method.
Before result : [system_usage_monitor_before.txt](https://github.com/user-attachments/files/17471791/system_usage_monitor_before.txt)
After result : [system_usage_monitor_after.txt](https://github.com/user-attachments/files/17471788/system_usage_monitor_after.txt)
The following information will be added when I use current the latest OSS Autoware.
```
+ | default_ad_api | initial_pose_adaptor_node                             |
+ | default_ad_api | routing_adaptor_node                                  |
+ | localization   | automatic_pose_initializer_node                       |
+ | localization   | ekf_localizer_node                                    |
+ | localization   | gyro_odometer_node                                    |
+ | localization   | …
```
> fix(system_usage_monitor): change the node search method

- control_data_collecting_tool/CMakeLists.txt
- control_data_collecting_tool/README.md
- control_data_collecting_tool/config/param.yaml
- control_data_collecting_tool/config/topics.yaml
- control_data_collecting_tool/launch/control_data_collecting_tool.launch.py
- control_data_collecting_tool/scripts/data_collecting_base_node.py
- control_data_collecting_tool/scripts/data_collecting_data_counter.py
- control_data_collecting_tool/scripts/data_collecting_plotter.py
- control_data_collecting_tool/scripts/data_collecting_rosbag_record.py
- control_data_collecting_tool/scripts/data_collecting_trajectory_publisher.py
- control_data_collecting_tool/scripts/rosbag_play.py
Add following two functionalities in this PR.
- Add a feature to stop when crossing the green line.
[pr_safety_measure.webm](https://github.com/user-attachments/assets/f062b68f-eab7-48e8-8e34-03d00111572d)
- Rosbag2 recording and loading functionalities
- When nodes are launched, topics in `config/topics.yaml` are automatically recorded and the data is saved in the directory where nodes are launched.
- The data from `/localization/kinematic_state` and `/localization/acceleration` located in the current directory. You can switch-off this functionality if `LOAD_ROSBAG2_FILES` in `config/param.yaml` is set to `false`.
Following demo shows control data collecting tool loads data in the current directory and automatically reflects data counting plots. …
> feat(control_data_collecting_tool): add safety measures and rosbag recording and loading

- common/tier4_string_viewer_rviz_plugin/src/string_viewer_panel.cpp
- common/tier4_string_viewer_rviz_plugin/src/string_viewer_panel.hpp
I fixed logic so that we can set default topic name in rviz config like this:
```yaml
- Class: tier4_string_viewer_rviz_plugin::StringViewerPanel
Name: StringViewerPanel
topic: /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/internal_state
```
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guide …
> feat(rviz): make it possible to set default topic name

- planning/planning_debug_tools/scripts/closest_velocity_checker.py
Fix `closest_velocity_checker.py`.  Use `autoware_adapi_v1_msgs` to check engage status.
> fix(planning_debug_tools): output engage status properly

- map/autoware_lanelet2_map_validator/src/common/validation.cpp
In the previous PR https://github.com/autowarefoundation/autoware_tools/pull/147, I've put a bug that `appendIssues()` will be executed twice. This PR removes the second `appendIssues()`.
(Output screen with bug)
(Output screen without bug)
This PR https://github.com/autowarefoundation/autoware_tools/pull/147 has a second `appendIssues()` in the final part of `lanelet::autoware::validation::validateMap()` while the one before that PR https://github.com/autowarefoundation/autoware_tools/pull/144 doesn't.
Checked that redundant issues disappear from the console output as shown in the upper image.
Checked that `colcon test` passed.
This bug doesn't affect the JSON output but affects the output from `lanelet::validation::printAllIssues(issues);` only.
None
Redundant console outputs no longer …
> fix(autoware_lanelet2_map_validator): removed redundant appendIssues()

- map/autoware_lanelet2_map_validator/src/validators/crosswalk/regulatory_element_details_for_crosswalks.cpp
- map/autoware_lanelet2_map_validator/src/validators/traffic_light/regulatory_element_details_for_traffic_lights.cpp
- map/autoware_lanelet2_map_validator/test/src/test_regulatory_element_details.cpp
This PR changes the order of validation in `regulatory_elements_details`.
The validator will **first** check whether there are empty attributes, and then will check the type of them are valid.
Thanks to this change the validator will NOT output two issues when the attribute type is wrong.
This bug was found through this PR https://github.com/autowarefoundation/autoware_tools/pull/150.
Because the PR above cannot pass the `colcon test` in the CI, this PR has to go first.
Test the codes through
```
colcon test --event-handlers console_cohesion+ --packages-select autoware_lanelet2_map_validator
```
Note that this change is mainly aimed to fix the bug found in the test made in PR https://github.com/autowarefoundation/autoware_tools/pull/150.
I had to change …
> fix(lanelet2_map_validator): change validation order in regulatory_elements_details

- bag2lanelet/scripts/bag2map.py
- planning/planning_debug_tools/README.md
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
- planning/planning_debug_tools/scripts/perception_replayer/utils.py
I added the pub-route option to perception_reproducer, enabling route generation using the first and last poses contained in the rosbag.
Previously, perception_reproducer execution and initial/goal pose setting had to be performed separately, but with this added functionality, that work is no longer necessary.
I have confirmed that routes are being generated successfully.
https://github.com/user-attachments/assets/4fbb8986-e278-46d1-a631-263a67f4c8f4 …
> feat(perception_reproducer): add publish route option

- map/autoware_lanelet2_map_validator/src/common/map_loader.cpp
- map/autoware_lanelet2_map_validator/src/common/validation.cpp
- map/autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/map_loader.hpp
- map/autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/utils.hpp
- map/autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validation.hpp
- map/autoware_lanelet2_map_validator/src/main.cpp
Current implementation tries to load the lanelet_map for each validation process which is inefficient and contaminates the report. With this PR, the map is loaded at first and then passed to each validation process. 
unit test passes
None
None
> refactor(lalenet2_map_validator): divide map loading process

- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
- planning/planning_debug_tools/scripts/perception_replayer/utils.py
fix the bug that perception_reproducer doesn't work when without '-p'.
> fix(perception_reproducer): fix a small bug

- system/rqt_diagnostic_graph_monitor/package.xml
Fix missing dependency of rqt_diagnostic_graph_monitor package.
None
1. Build with `--packages-up-to rqt_diagnostic_graph_monitor` option
2. Run rqt_diagnostic_graph_monitor
None
None
None
> fix(rqt_diagnostic_graph_monitor): add missing dependency

- map/autoware_lanelet2_map_validator/src/common/validation.cpp
This PR fixes the issue that the validation results (lanelet2_validation_results.json) don't reflect the prerequisite failure.
The content in `prerequisite_issues` should be written in the JSON objects, but the process between L319 to L355 (in validation.cpp) is skipped only for `prerequisite_issues`.
None
- Checked that `colcon test` has passed.
- Checked that issues with a message "Prerequisites didn't pass." appear in `lanelet2_map_validation_results.json` when a incomplete lanelet2 map is given.
Prerequisites failure will appear in the results as expected.
After all checkboxes are …
> fix(lanelet2_map_validator): fixed issue that invalid prerequisites are not reflected to the results

- driving_environment_analyzer/package.xml
- driving_environment_analyzer/src/utils.cpp
`lanelet2_extension` has been replaced by `autoware_lanelet2_extension`.
- https://github.com/autowarefoundation/autoware/pull/5578
Without this PR, the following error occurs. 
```bash
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
driving_environment_analyzer: Cannot locate rosdep definition for [lanelet2_extension]
```
None.
None.
> fix: to use autoware_lanelet2_extension

- common/tier4_debug_rviz_plugin/include/tier4_debug_rviz_plugin/string_stamped.hpp
- common/tier4_debug_rviz_plugin/package.xml
- common/tier4_debug_rviz_plugin/plugins/plugin_description.xml
- common/tier4_debug_rviz_plugin/src/string_stamped.cpp
- common/tier4_string_viewer_rviz_plugin/README.md
- common/tier4_string_viewer_rviz_plugin/package.xml
- common/tier4_string_viewer_rviz_plugin/src/string_viewer_panel.hpp
The message used in this repository will be moved by https://github.com/autowarefoundation/autoware_internal_msgs/pull/30
This PR will handle this change.
Run the following command, and manually add autoware_internal_debug_msgs in the package.xml
```
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs::msg::StringStamped/autoware_internal_debug_msgs::msg::StringStamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs\/msg\/string_stamped/autoware_internal_debug_msgs\/msg\/string_stamped/g' {} \;
```
None.
None.
> feat(tier4_xxx_rviz_plugin): use StringStamped in autoware_internal_debug_msgs

- common/autoware_debug_tools/autoware_debug_tools/system_performance_plotter/cpu_usage_plotter.py
- common/autoware_debug_tools/autoware_debug_tools/system_performance_plotter/memory_usage_plotter.py
- common/autoware_debug_tools/autoware_debug_tools/system_performance_plotter/processing_time_plotter.py
- common/autoware_debug_tools/autoware_debug_tools/system_performance_plotter/system_performance_plotter_base.py
Use autoware_internal_debug_msgs in processing_time_plotter.py based on the following issues
https://github.com/autowarefoundation/autoware/issues/5580
None.
None.
> feat: use autoware_internal_debug_msgs in processing_time_plotter.py

- map/autoware_lanelet2_map_validator/README.md
update cli usage
document PR
None.
None.
> docs(autoware_lanelet2_map_validator): update usage

- map/autoware_lanelet2_map_validator/test/data/map/intersection/basic_intersection_area.osm
- map/autoware_lanelet2_map_validator/test/data/map/intersection/intersection_area_with_dangling_reference.osm
- map/autoware_lanelet2_map_validator/test/data/map/intersection/intersection_area_with_irrelative_point.osm
- map/autoware_lanelet2_map_validator/test/data/map/intersection/intersection_area_with_self_intersection.osm
- map/autoware_lanelet2_map_validator/test/data/map/intersection/intersection_area_with_wrong_linestring_type.osm
- map/autoware_lanelet2_map_validator/test/data/map/intersection/intersection_area_with_wrong_orientation.osm
- map/autoware_lanelet2_map_validator/test/data/map/sample_map.osm
I found that one of the intersection lanes were removed by accident.
This PR restores that lane and removed unnecessary linestrings from intersection test maps.
The left figure is the current `basic_intersection_area.osm`. The red rectangle implies the missing lane.
The right figure is the one fixed in this PR.
Checked that following command runs without errors.
```bash
colcon test --packages-select autoware_lanelet2_map_validator --event-handlers console_cohesion+
```
The two maps below have large changes since they were not made from vector map builder but have been edited through vector map builder in this PR.
- `basic_intersection_area.osm`
- `intersection_area_with_wrong_orientation.osm`
None.
> fix(lanelet2_map_validator): restore missing intersection lane and removed unnecessary linestrings from intersection test maps

- common/autoware_sample_vehicle_description/CMakeLists.txt
- common/autoware_sample_vehicle_description/config/mirror.param.yaml
- common/autoware_sample_vehicle_description/config/simulator_model.param.yaml
- common/autoware_sample_vehicle_description/config/vehicle_info.param.yaml
- common/autoware_sample_vehicle_description/package.xml
- common/autoware_sample_vehicle_description/urdf/vehicle.xacro
- planning/autoware_static_centerline_generator/CMakeLists.txt
- planning/autoware_static_centerline_generator/launch/static_centerline_generator.launch.xml
- planning/autoware_static_centerline_generator/package.xml
- planning/autoware_static_centerline_generator/test/test_static_centerline_generator.test.py
- planning/autoware_static_centerline_generator/test/test_static_centerline_generator_launch.test.py
depends on https://github.com/autowarefoundation/autoware_tools/pull/189
Added a test for static_centerline_generator.launch.xml.
Since the launch.xml uses the global_parameter_loader of vehicle_launch, this PR also added a sample_vehicle_launch just for testing.
Unit test passed.
None.
None.
> test(static_centerline_generator): add launch test with autoware_sample_vehicle_launch package

- map/autoware_lanelet2_map_validator/autoware_requirement_set.json
- map/autoware_lanelet2_map_validator/docs/intersection/turn_direction_tagging.md
- map/autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validators/intersection/turn_direction_tagging.hpp
- map/autoware_lanelet2_map_validator/src/validators/intersection/turn_direction_tagging.cpp
- map/autoware_lanelet2_map_validator/test/data/map/intersection/intersection_area_with_invalid_turn_direction_tag.osm
- map/autoware_lanelet2_map_validator/test/data/map/intersection/intersection_area_without_straight_tag.osm
- map/autoware_lanelet2_map_validator/test/src/intersection/test_turn_direction_tagging.cpp
This PR adds a validator `mapping.intersection.turn_direction_tagging` that checks whether lanelets in intersections have `turn_direction` tags and their values are `left`, `right`, or `straight`.
In short, this PR adds the following implementation.
- New validator `mapping.intersection.turn_direction_tagging` that detects lanelets that belong to intersections but don't have a valid `turn_direction` tag.
- A test code for `mapping.intersection.turn_direction_tagging`.
- A document for `mapping.intersection.turn_direction_tagging`.
- Added `mapping.intersection.turn_direction_tagging` to `autoware_requirement_set.json`
1. Confirmed that `colcon test --packages-select autoware_lanelet2_map_validator --event-handlers console_cohesion+` passes.
2. Confirmed that the following command shows no …
> feat(lanelet2_map_validator): add validator to check whether intersection lanelets have valid turn_direction tags

- planning/autoware_static_centerline_generator/launch/static_centerline_generator.launch.xml
- planning/autoware_static_centerline_generator/package.xml
- planning/autoware_static_centerline_generator/src/static_centerline_generator_node.cpp
- planning/autoware_static_centerline_generator/test/test_static_centerline_generator.test.py
- planning/autoware_static_centerline_generator/test/test_static_centerline_generator_launch.test.py
This updates the packages that depends on autoware_mission_planner to use updated name in https://github.com/autowarefoundation/autoware.universe/pull/9941
Tested with planning simulator
None.
None.
> feat(autoware_static_centerline_generator): rename autoware_mission_planner to autoware_mission_planner_universe

- localization/deviation_estimation_tools/deviation_estimator/include/deviation_estimator/deviation_estimator.hpp
- localization/deviation_estimation_tools/deviation_estimator/include/deviation_estimator/utils.hpp
- localization/deviation_estimation_tools/deviation_estimator/include/deviation_estimator/velocity_coef_module.hpp
- localization/deviation_estimation_tools/deviation_estimator/package.xml
- localization/deviation_estimation_tools/deviation_estimator/src/deviation_estimator.cpp
- localization/deviation_estimation_tools/deviation_estimator/src/deviation_estimator_main.cpp
- localization/deviation_estimation_tools/deviation_estimator/src/utils.cpp
- localization/deviation_estimation_tools/deviation_evaluator/include/deviation_evaluator/deviation_evaluator.hpp
- localization/deviation_estimation_tools/deviation_evaluator/package.xml
None. It seems like it is only used for internal calculation.
I have tested that the node launch without an error with 
```sh
ros2 launch deviation_estimator deviation_estimator.launch.xml
```
None.
None.
> feat(deviation_estimation_tools): replace tier4_debug_msgs with tier4_internal_debug_msgs

- planning/autoware_planning_data_analyzer/README.md
- planning/autoware_planning_data_analyzer/package.xml
- planning/autoware_planning_data_analyzer/src/type_alias.hpp
|  Pub | `~/output/manual_metrics` | `tier4_debug_msgs/Float32MultiArrayStamped` | `autoware_internal_debug_msgs/Float32MultiArrayStamped` |
|  Pub | `~/output/system_metrics` | `tier4_debug_msgs/Float32MultiArrayStamped` | `autoware_internal_debug_msgs/Float32MultiArrayStamped` |
|  Pub | `~/output/manual_score` | `tier4_debug_msgs/Float32MultiArrayStamped` | `autoware_internal_debug_msgs/Float32MultiArrayStamped` |
|  Pub | `~/output/system_score` | …
> feat(autoware_planning_data_analyzer)!: replace tier4_debug_msgs with tier4_internal_debug_msgs

- planning/planning_debug_tools/include/planning_debug_tools/trajectory_analyzer.hpp
- planning/planning_debug_tools/package.xml
- planning/planning_debug_tools/scripts/closest_velocity_checker.py
- planning/planning_debug_tools/scripts/processing_time_checker.py
velocity_checker
|  Pub | `~/closest_speeds` | `tier4_debug_msgs/Float32MultiArrayStamped` | `autoware_internal_debug_msgs/Float32MultiArrayStamped` |
|  Sub | `scenario + "/motion_velocity_smoother/distance_to_stopline` | `tier4_debug_msgs/Float32Stamped` | `autoware_internal_debug_msgs/Float32Stamped` |
processing_time_checker
|:---------------------|:------------------|:---------------- …
> feat(planning_debug_tools)!: replace tier4_debug_msgs with tier4_internal_debug_msgs

- control/stop_accel_evaluator/include/stop_accel_evaluator/stop_accel_evaluator_node.hpp
- control/stop_accel_evaluator/package.xml
|  Pub | `~/stop_accel` | `tier4_debug_msgs/Float32Stamped` | `autoware_internal_debug_msgs/Float32Stamped` |
|  Pub | `~/stop_accel_with_gravity` | `tier4_debug_msgs/Float32Stamped` | `autoware_internal_debug_msgs/Float32Stamped` |
None.
None.
> feat(stop_accel_evaluator)!: replace tier4_debug_msgs with tier4_internal_debug_msgs

- common/tier4_debug_rviz_plugin/README.md
- common/tier4_debug_rviz_plugin/include/tier4_debug_rviz_plugin/float32_multi_array_stamped_pie_chart.hpp
- common/tier4_debug_rviz_plugin/package.xml
- common/tier4_debug_rviz_plugin/plugins/plugin_description.xml
- common/tier4_debug_rviz_plugin/src/float32_multi_array_stamped_pie_chart.cpp
|  Sub | selected input topic in plugin | `tier4_debug_msgs/Float32MultiArrayStamped` | `autoware_internal_debug_msgs/Float32MultiArrayStamped` |
I have confirmed with planning_simulator that the plugin can be loaded and can be subscribed to autoware_internal_debug_msgs/Float32MultiArrayStamped
None.
None.
> feat(tier4_debug_rviz_plugin)!: replace tier4_debug_msgs with tier4_internal_debug_msgs

- common/tier4_debug_tools/include/tier4_debug_tools/lateral_error_publisher.hpp
- common/tier4_debug_tools/package.xml
- common/tier4_debug_tools/src/lateral_error_publisher.cpp
|  Pub | `~/control_lateral_error` | `tier4_debug_msgs/Float32Stamped` | `autoware_internal_debug_msgs/Float32Stamped` |
|  Pub | `~/localization_lateral_error` | `tier4_debug_msgs/Float32Stamped` | `autoware_internal_debug_msgs/Float32Stamped` |
|  Pub | `~/lateral_error` | `tier4_debug_msgs/Float32Stamped` | `autoware_internal_debug_msgs/Float32Stamped` |
I have confirmed that the node launch successfully with the following command and confirmed that output topic is …
> feat(tier4_debug_tools)!: replace tier4_debug_msgs with tier4_internal_debug_msgs

- control/vehicle_cmd_analyzer/include/vehicle_cmd_analyzer/vehicle_cmd_analyzer.hpp
- control/vehicle_cmd_analyzer/package.xml
- control/vehicle_cmd_analyzer/src/vehicle_cmd_analyzer.cpp
|  Pub | `~/debug_values` | `tier4_debug_msgs/Float32MultiArrayStamped` | `autoware_internal_debug_msgs/Float32MultiArrayStamped` |
I have tested with the following:
* launch planning simulator
* launch `ros2 launch vehicle_cmd_analyzer vehicle_cmd_analyzer.launch.xml vehicle_model:=lexus`
Confirmed that there are no tier4_debug_msgs
None.
None.
> feat(vehicle_cmd_analyzer)!: replace tier4_debug_msgs with tier4_internal_debug_msgs

- vehicle/parameter_estimator/include/parameter_estimator/debugger.hpp
- vehicle/parameter_estimator/package.xml
|  Pub | `~/debug_values/*` | `tier4_debug_msgs/Float32MultiArrayStamped` | `autoware_internal_debug_msgs/Float32MultiArrayStamped` |
I have confirmed that the node can be launched with the following command and confirmed that topics are published with the updated message type
```sh
ros2 launch parameter_estimator parameter_estimator.launch.xml vehicle_model:=sample_vehicle
```
None.
None.
> feat(parameter_estimator)!: replace tier4_debug_msgs with tier4_internal_debug_msgs

- map/autoware_lanelet2_map_validator/docs/lane/local_coordinates_declaration.md
- map/autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/validators/lane/local_coordinates_declaration.hpp
- map/autoware_lanelet2_map_validator/src/validators/lane/local_coordinates_declaration.cpp
- map/autoware_lanelet2_map_validator/test/data/map/lane/single_lanelet.osm
- map/autoware_lanelet2_map_validator/test/data/map/lane/single_lanelet_first_three_points_missing_local_coordinates.osm
- map/autoware_lanelet2_map_validator/test/data/map/lane/single_lanelet_partially_defected_local_coordinates.osm
- map/autoware_lanelet2_map_validator/test/data/map/lane/single_lanelet_without_local_coordinates.osm
- map/autoware_lanelet2_map_validator/test/src/lane/test_local_coordinates_declaration.cpp
This PR adds a validator `mapping.intersection.local_coordinates_declaration` that checks whether all points have `local_x` & `local_y` or all points don't have `local_x` and `local_y`.
In short, this PR adds the following implementation.
- New validator `mapping.intersection.local_coordinates_declaration`.
- A test code for `mapping.intersection.local_coordinates_declaration`.
- A document for `mapping.intersection.local_coordinates_declaration`.
1. Confirmed that `colcon test --packages-select autoware_lanelet2_map_validator --event-handlers console_cohesion+` passes.
2. Confirmed that the following command shows no mistakes against several lanelet2 maps I have.
```
ros2 run autoware_lanelet2_map_validator autoware_lanelet2_map_validator -p mgrs -m <PATH_TO_sample_map.osm> -i …
```
> feat(lanelet2_map_validator): check local coordinates declaration

- driving_environment_analyzer/src/utils.cpp
This adds include declaration to many packages that are using functions from autoware_universe_utils.
This was found when I was working on removing Autoware.Universe dependencies from autoware_interpolation and autoware_motion_utils packages for Autoware Core porting activity. Currently, many packages seemed to include autoware_universe_utils header files via autoware_interpolation or autoware_motion_utils, and outputs a lot of errors when we modify autoware_interpolation and autoware_motion_utils package dependencies.
This PR will make sure that each package independently includes headers that they use in their code as a preparation.
I have made sure that it builds without an error.
None.
None.
> fix(driving_environment_analyzer): add missing include files for autoware_universe_utils

- localization/autoware_localization_evaluation_scripts/CMakeLists.txt
- localization/autoware_localization_evaluation_scripts/README.md
- localization/autoware_localization_evaluation_scripts/scripts/compare_trajectories.py
- localization/autoware_localization_evaluation_scripts/scripts/extract_pose_from_rosbag.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/calc_relative_pose.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/interpolate_pose.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/parse_functions.py
This pull request adds 2 main scripts and 3 utility scripts.
- `extract_pose_from_rosbag.py`
- `compare_trajectories.py`
```bash
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py \
scenario_path:=$HOME/driving_log_replayer_v2/localization.yaml
ros2 run autoware_localization_evaluation_scripts extract_pose_from_rosbag.py \
$HOME/driving_log_replayer_v2/out/latest/result_bag \
--target_topics "/localization/kinematic_state" \
"/localization/pose_estimator/pose_with_covariance"
ros2 run autoware_localization_evaluation_scripts compare_trajectories.py \
$HOME/driving_log_replayer_v2/out/latest/pose_tsv/localization__kinematic_state.tsv \
$HOME/driving_log_replayer_v2/out/latest/pose_tsv/localization__pose_estimator__pose_with_covariance.tsv
```
None.
None.
> feat: add `compare_trajectories.py` and `extract_pose_from_rosbag.py`

- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/parse_functions.py
This pull request changes `analyze_rosbags_parallel.py` to be able to specify a rosbag instead of the parent directory.
[NITS]
* I deleted the remaining Japanese comments.
The following commands both work.
* Specify the parent directory.
```bash
ros2 run autoware_localization_evaluation_scripts analyze_rosbags_parallel.py \
$HOME/driving_log_replayer_v2/out/ \
--parallel_num 2 \
--topic_subject "/localization/kinematic_state" \
--topic_reference "/localization/pose_estimator/pose_with_covariance"
```
* Specify one directory.
```bash
ros2 run autoware_localization_evaluation_scripts analyze_rosbags_parallel.py \
$HOME/driving_log_replayer_v2/out/2025-0310-085140 \
--parallel_num 2 \
--topic_subject "/localization/kinematic_state" \
--topic_reference …
```
> fix(autoware_localization_evaluation_scripts): change target directories

- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
This pull request changes `analyze_rosbags_parallel.py` to be able to specify a specify the destination path relative to the directory where rosbag is located
```shell
ros2 run autoware_localization_evaluation_scripts analyze_rosbags_parallel.py \
$HOME/dlr2_data/localization/out/2025-0310-151452 \
--save_dir_relative \
result_archive
~/dlr2_data/localization/out/2025-0310-151452
❯ tree
.
├── result.jsonl
├── result_archive
│   ├── compare_trajectories
│   │   ├── localization__kinematic_state.tsv
│   │   ├── localization__kinematic_state_result
│   │   │   ├── compare_trajectories.png
│   │   │   ├── relative_pose.png
│   │   │   ├── relative_pose.tsv
│   │   │   └── relative_pose_summary.tsv
│   │   └── localization__pose_estimator__pose_with_covariance.tsv
│   └── diagnostics_result …
```
> fix: set save dir

- localization/autoware_localization_evaluation_scripts/scripts/plot_diagnostics.py
Fix a bug.
|Before|After|
|:-------:|:-----:|
|<img src="https://github.com/user-attachments/assets/e6f9bb7e-107d-46f9-8261-a1afaf6919a6" width=500 />|<img src="https://github.com/user-attachments/assets/5d6e541c-7d8c-4274-8ac1-47a3054d7446" width=500 />|
```bash
ros2 run autoware_localization_evaluation_scripts analyze_rosbags_parallel.py \
$HOME/driving_log_replayer_v2/out/latest \
--parallel_num 2 \
--topic_subject "/localization/kinematic_state" \
--topic_reference "/localization/reference_kinematic_state"
```
None.
None.
> fix(autoware_localization_evaluation_scripts): add `plt.close()`

- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/node.py
- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/tree.py
The "ProcessingTimeXXX" message was ported from tier4_debug_msgs to autoware_internal_debug_msgs, but the autoware_tools which depends on the message was not updated. This PR fixes the issue.
`ros2 run autoware_debug_tools processing_time_visualizer` can show the processing time tree successfully.
None.
None.
> fix(autoware_debug_tools): time keeper does not work with the old message type

- build_depends.repos
- planning/planning_debug_tools/scripts/closest_velocity_checker.py
- planning/planning_debug_tools/scripts/trajectory_visualizer.py
This replaces tier4_planning_msgs with autoware_internal_planning_msgs for VelocityLimit as part of porting packages to Autoware Core.
This must be merged with https://github.com/autowarefoundation/autoware.universe/pull/10273.
I have ran trajectory_visualizer with planning_simulator
None.
None.
> feat(planning_debug_tools)!: replace VelocityLimit messages to autoware_internal_planning_msgs

- planning/autoware_static_centerline_generator/launch/static_centerline_generator.launch.xml
This PR fix mission_planner parameter path in static_centerline_generator launch file
[TIER IV internal link](https://star4.slack.com/archives/CEV8XMJBV/p1741067486622319?)  
static path was generated successfully
None.
None.
> fix: mission_planner parameter path in static_centerline_generator launch file

- common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.cpp
- common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.hpp
- common/tier4_screen_capture_rviz_plugin/srv/Capture.srv
add buffer size configuration and update handling
- can change buffer seconds from rviz 
- can change buffer seconds from service communication
https://github.com/user-attachments/assets/86ecb509-1e38-46d8-b63c-ea2ada53dec7
https://github.com/user-attachments/assets/2cf6ca55-edc2-427d-bfc8-94d4d6e33618
change video duration with following command
```
ros2 service call /debug/capture tier4_screen_capture_rviz_plugin/srv/Capture "{action: 6, buffer_seconds: "5"}"
```
and get 5 sec video
https://github.com/user-attachments/assets/bab80a44-08c0-450e-884e-d978be989ba4
None.
None.
> feat(tier4_screen_capture_rviz_plugin): add buffer change bottom

- .github/sync-files.yaml
- .github/workflows/spell-check-all.yaml
- .github/workflows/spell-check-differential.yaml
- https://github.com/autowarefoundation/autoware_tools/pull/11 has updated these files but it seems we forgot to add the existing local `.cspell-partial.json` file.
This PR adds that.
Related PR that made us realize this issue:
- https://github.com/autowarefoundation/autoware_tools/pull/231
Additional changes:
- Updated `spell-check-all.yaml` dict-packages to match `spell-check-differential.yaml`.
- Removed from the sync-files.yaml to manage these files manually.
**Also fixed:**
None.
None.
> ci(spell-check*): add missing .cspell-partial reference and missing dicts

- localization/autoware_localization_evaluation_scripts/CMakeLists.txt
- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
- localization/autoware_localization_evaluation_scripts/scripts/extract_values_from_rosbag.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/parse_functions.py
This pull request changes the script so that the acceleration topic can be extracted. As a result, the script name has been partially revised.
```
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py \
play_rate:=1.0 \
storage:=mcap \
scenario_path:=$HOME/driving_log_replayer_v2/localization.yaml
```
The results were
```
~/driving_log_replayer_v2/out/latest$ tree .
.
├── result.jsonl
├── result_archive
│   ├── compare_trajectories
│   │   ├── localization__kinematic_state.tsv
│   │   ├── localization__kinematic_state_result
│   │   │   ├── compare_trajectories.png
│   │   │   ├── relative_pose.png
│   │   │   ├── relative_pose.tsv
│   │   │   └── relative_pose_summary.tsv
│   │   └── localization__reference_kinematic_state.tsv
│   ├── diagnostics_result
│   │   ├── …
```
> feat(autoware_localization_evaluation_scripts): add parse accel

- build_depends.repos
- common/autoware_sample_vehicle_description/package.xml
[Build error](https://github.com/autowarefoundation/autoware_tools/actions/runs/14583882988/job/40905811547?pr=234) in `autoware_geography_utils`
```
--- stderr: autoware_geography_utils
/__w/autoware_tools/autoware_tools/dependency_ws/core/autoware.core/common/autoware_geography_utils/src/lanelet2_projector.cpp: In function ‘std::unique_ptr<lanelet::Projector> autoware::geography_utils::get_lanelet2_projector(const MapProjectorInfo&)’:
/__w/autoware_tools/autoware_tools/dependency_ws/core/autoware.core/common/autoware_geography_utils/src/lanelet2_projector.cpp:52:42: error: no matching function for call to ‘lanelet::projection::format_v2::TransverseMercatorProjector::TransverseMercatorProjector(<brace-enclosed initializer list>)’
52 |       origin, projector_info.scale_factor};
| …
```
> feat(build_depends.repos): update autoware_lanelet2_extension v0.7.0

- build_depends.repos
- Some packages related to Autoware are version-locked
- Some Autoware-related packages are branch specific
This situation makes it difficult to pass builds when changes are made that depend on multiple repositories.
To solve this, revert all Autoware and universe packages to branches.
None.
None.
> feat(build_depends.repos): use fixed version for autoware and universe repository

- .github/workflows/build-and-test-differential.yaml
- See: https://github.com/autowarefoundation/autoware_universe/pull/10677
None.
None.
> ci(build-and-test-diff): use self hosted runners

- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/calc_relative_pose.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/interpolate_pose.py
Correspond to https://github.com/tier4/driving_log_replayer_v2/pull/165
This PR adds computation and output of a `summary.json` file capturing position, angle, linear velocity, and angular velocity metrics for localization evaluation.
- Extend interpolation to include linear and angular velocity
- Compute relative velocity norms alongside pose differences
- Generate `summary.json` with thresholds and pass/fail summary in the parallel analysis script
`summary.json` is used for [driving_log_replayer_v2](https://github.com/tier4/driving_log_replayer_v2).
`driving_log_replayer_v2` outputs a `result.jsonl` and the final line of that file is treated as the total result of the test case.
Evaluator test -> [TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/40a651b0-d3f3-5222-8fbd-93 …
> feat: add `summary.json`

- localization/autoware_localization_evaluation_scripts/scripts/utils/calc_relative_pose.py
Fixed the `calc_relative_pose.py` script so that it can be used  with a pose-only tsv file.
Applied to `localization/pose_twist_fusion_filter/pose`
```bash
ros2 run autoware_localization_evaluation_scripts compare_trajectories.py \
/home/shintarosakoda/data/misc/20250617_130521_ndt/localization__pose_twist_fusion_filter__pose.tsv \
/home/shintarosakoda/data/misc/20250617_130521_ndt/awsim__ground_truth__localization__kinematic_state.tsv
```
None.
None.
> fix: to apply to a pose only tsv file

- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/calc_acceleration_diff.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/calc_relative_pose.py
- localization/autoware_localization_evaluation_scripts/scripts/utils/interpolate_pose.py
This PR adds acceleration evaluation functionality to the localization evaluation scripts. The main change is adding acceleration difference calculation between measured and reference trajectories, improving the robustness of localization evaluation by making velocity-related checks optional when data is not available.
```bash
source ~/autoware/install/setup.bash
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py \
play_rate:=1.0 \
storage:=mcap \
scenario_path:=$HOME/driving_log_replayer_v2/localization.yaml
```
then, check
```bash
ls ~/driving_log_replayer_v2/out/latest/result_archive/result_acceleration/
localization__acceleration.tsv  localization__acceleration_diff.tsv
```
None.
None.
> feat: add acceleration evaluation

- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
This PR updates the localization evaluation criteria by changing the input file variable names, filtering logic, and the threshold logic for determining localization success.
- Renamed the diagnostics file variable for clarity.
- Added an extra condition to filter out "Node is not activated." messages.
- Updated the failure threshold from 1% to 5%.
```bash
source ~/autoware/install/setup.bash
ros2 launch driving_log_replayer_v2 driving_log_replayer_v2.launch.py \
play_rate:=1.0 \
scenario_path:=$HOME/driving_log_replayer_v2/localization.yaml
```
None.
None.
> fix: change the criteria for localization 

- planning/autoware_static_centerline_generator/README.md
- planning/autoware_static_centerline_generator/src/utils.cpp
- Fixed so that a single point centerline is not generated.
- Fixed incorrect argument in readme.
Local test
```sh
ros2 launch autoware_static_centerline_generator static_centerline_generator.launch.xml run_backgrond:=true lanelet2_input_file_path:=$HOME/map/one_centerline_test/lanelet2_map.osm start_lanelet_id:=203 start_pose:=[35970.342,56058.19,37.4566,0.0,0.0,-0.883,0.46924]  end_lanelet_id:=12544 end_pose:=[35928.0,55981.745,37.384,0.0,0.0,0.8729,0.48788] vehicle_model:=cargo_transport goal_method:=path_generator
```
- [TIER IV Internal map_link](https://tools.tier4.jp/vector_map_builder_ll2/?projectId=autoware_dev&areaMapId=1235&versionId=1235-20250611102924054472)
None.
None.
> fix(static_centerline_generator): do not embed a single point centerline

- vehicle/parameter_estimator/launch/parameter_estimator_with_simulation.launch.xml
- vehicle/parameter_estimator/package.xml
The following packages were modified in the PR, but their dependencies could not be resolved, so they were corrected.
* https://github.com/autowarefoundation/autoware_tools/pull/214
- Updated vehicle_launch → tier4_vehicle_launch
- Updated map_launch → tier4_map_launch
- Removed dependency on the deleted dynamic_object_visualization package
rosdep install was successful and local build test successful.
```sh
$ rosdep install --from-paths src --ignore-src -y --rosdistro humble
#All required rosdeps installed successfully
```
None.
None.
> fix(parameter_estimatior): update package dependencies

- .github/workflows/build-and-test.yaml
- build_depends.repos
- planning/autoware_static_centerline_generator/CMakeLists.txt
- planning/autoware_static_centerline_generator/test/test_static_centerline_generator_gui_launch.test.py
- planning/autoware_static_centerline_generator/test/utils/test_utils.py
Fixes continuously failing https://github.com/autowarefoundation/autoware_tools/actions/workflows/build-and-test.yaml?query=branch%3Amain workflow.
- https://github.com/autowarefoundation/autoware_tools/actions/runs/16639474474/job/47086953489
This jlumbroso/free-disk-space@v1.2.0 is not meant for running in containers. It is meant for workflows that run on github public runners without containers.
- https://github.com/autowarefoundation/autoware_tools/actions/runs/16657382337 ❌
- It seems the container name was old too. Updated it with https://github.com/autowarefoundation/autoware_tools/pull/283/commits/af6d9aaf714a578ace913cd8ffd0032edafb180e
- https://github.com/autowarefoundation/autoware_tools/actions/runs/16657441513 ❌
- Failed due to version mismatch of autoware_lanelet2_extension …
> ci(build-and-test): fix ci issues

- planning/autoware_static_centerline_generator/package.xml
This PR fixes dependency for autoware_static_centerline_generator.
The package uses Qt5 for execution, but it does not have the library as dependency.
This is causing a failure in build-and-test-differential-above in Autoware Core.
https://github.com/autowarefoundation/autoware_core/actions/runs/16671444714/job/47188492044?pr=593
The test passes in CI. 
None.
None.
> fix(autoware_static_centerline_generator): fix test dependency

- planning/planning_debug_tools/scripts/trajectory_visualizer/config.yaml
Show motion velocity planner output by default.
```patch
diff --git a/planning/planning_debug_tools/scripts/trajectory_visualizer/config.yaml b/planning/planning_debug_tools/scripts/trajectory_visualizer/config.yaml
index c987fa9..e26ed1c 100644
--- a/planning/planning_debug_tools/scripts/trajectory_visualizer/config.yaml
+++ b/planning/planning_debug_tools/scripts/trajectory_visualizer/config.yaml
@@ -1,5 +1,6 @@
initial_topics: # initial topics to plot and their type
- [/planning/scenario_planning/trajectory, Trajectory]
+  - [/planning/scenario_planning/lane_driving/trajectory, Trajectory]
- [/planning/scenario_planning/lane_driving/motion_planning/path_optimizer/trajectory, Trajectory]
- [/planning/scenario_planning/lane_driving/behavior_planning/path, Path]
- …
```
> fix: show motion velocity planner output by default

- localization/autoware_localization_evaluation_scripts/README.md
- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
Currently, autoware_localization_evaluation_scripts can only provide the success/failure result by taking the AND condition of all criteria.This PR enables autoware_localization_evaluation_scripts to toggle whether to use the criterion or not for the final summary.
The mask is expected to be provided from the scenario file by adding a condition like the following.
Note that passing a scenario file is optional and the script will manage the masks as true if no scenario file is given OR there is no `OverallCriteriaMask` condition in the scenario file. So after this PR is merged, the existing evaluation through driving_log_replayer doesn't change at all.
Read the modified `README.md` for further information.
```yaml
Evaluation:
Conditions:
OverallCriteriaMask:
mean_relative_position: false …
```
> feat(autoware_localization_evaluation_scripts): create masks for each criterion

- localization/autoware_localization_evaluation_scripts/CMakeLists.txt
- localization/autoware_localization_evaluation_scripts/README.md
- localization/autoware_localization_evaluation_scripts/scripts/analyze_rosbags_parallel.py
- localization/autoware_localization_evaluation_scripts/scripts/diagnostics_flag_check.py
This PR adds a new evaluation script `diagnostics_flag_check.py` to detect the rise or fall of the localization diagnostics.
Currently this script only detects the rise/fall of `pose_is_passed_delay_gate` and `pose_no_update_count` (from ekf_localizer).
The condition can be read from the scenario file if it has a condition block like this.
```yaml
Evaluation:
Conditions:
DiagnosticsFlagCheck:
pose_is_passed_delay_gate:
flag: rise
at_sec: 113
at_nanosec: 750000000
```
This example means that the diagnostics `pose_is_passed_delay_gate` should rise at 113.75 sec in the rosbag time. To be more specific, the flag should rise within a time window of ±0.2 seconds around the target time.
Tested that it works as expected with driving_log_replayer scenario.
[INTERNAL_LINK(Evaluation …
> feat(autoware_localization_evaluation_scripts): detect rise/fall flags of localization diagnostics
