- build_depends.repos
- planning/planning_debug_tools/README.md
> docs(planning_debug_tools): fix reactive script example

- build_depends.repos
CI was failing because of missing dependency, prevent PRs to be merged
> fix(.repos): add autoware_internal_msgs dependency

- localization/deviation_estimation_tools/deviation_evaluator/launch/deviation_evaluator.launch.xml
- localization/deviation_estimation_tools/deviation_evaluator/scripts/bag_load_utils.py
Fixed so that cspell warning does not appear.
> fix(localization): fix to pass cspell about localization

- .github/workflows/build-and-test-differential.yaml
- .github/workflows/build-and-test.yaml
So many things were outdated or wrong, manually fixing them for now, soon I will fix the sync-files configuration for this repository too.
> ci(build-and-test): and differential ci fixes

- bag2lanelet/scripts/bag2map.py
- driving_environment_analyzer/package.xml
remove `<depend>vehicle_info_util</depend>`
> fix(driving_environment_analyzer): fix unused package dependency

- driving_environment_analyzer/include/driving_environment_analyzer/analyzer_core.hpp
- driving_environment_analyzer/include/driving_environment_analyzer/type_alias.hpp
https://github.com/autowarefoundation/autoware.universe/pull/7530
> refactor(route_handler)!: include autoware_route_handler

- common/tier4_automatic_goal_rviz_plugin/src/automatic_goal_panel.cpp
- common/tier4_debug_tools/src/lateral_error_publisher.cpp
- control/stop_accel_evaluator/include/stop_accel_evaluator/stop_accel_evaluator_node.hpp
- control/stop_accel_evaluator/src/stop_accel_evaluator_node.cpp
- driving_environment_analyzer/src/utils.cpp
- localization/deviation_estimation_tools/deviation_estimator/include/deviation_estimator/autoware_universe_utils.hpp
- localization/deviation_estimation_tools/deviation_estimator/include/deviation_estimator/deviation_estimator.hpp
- localization/deviation_estimation_tools/deviation_estimator/src/deviation_estimator.cpp
- localization/deviation_estimation_tools/deviation_estimator/src/utils.cpp
- localization/deviation_estimation_tools/deviation_estimator/test/test_gyro_bias.cpp
- localization/deviation_estimation_tools/deviation_estimator/test/test_gyro_stddev.cpp
- localization/deviation_estimation_tools/deviation_evaluator/include/deviation_evaluator/autoware_universe_utils.hpp
- localization/deviation_estimation_tools/deviation_evaluator/include/deviation_evaluator/deviation_evaluator.hpp
- localization/deviation_estimation_tools/deviation_evaluator/src/deviation_evaluator.cpp
- planning/planning_debug_tools/include/planning_debug_tools/trajectory_analyzer.hpp
- planning/planning_debug_tools/include/planning_debug_tools/util.hpp
- planning/planning_debug_tools/src/stop_reason_visualizer.cpp
- vehicle/pitch_checker/include/pitch_checker/pitch_checker.hpp
- vehicle/pitch_checker/src/pitch_checker_node.cpp
change namespace
autoware_motion_utils -> autoware::motion_utils
autoware_universe_utils -> autoware::universe_utils
https://github.com/autowarefoundation/autoware.universe/pull/7594
> refactor(universe_utils/motion_utils)!: add autoware namespace

- planning/planning_debug_tools/scripts/closest_velocity_checker.py
- simulator/simulator_compatibility_test/simulator_compatibility_test/publishers/ackermann_control_command.py
- simulator/simulator_compatibility_test/test_base/test_03_longitudinal_command_and_report.py
- simulator/simulator_compatibility_test/test_base/test_04_lateral_command_and_report.py
fix 
https://github.com/autowarefoundation/autoware_tools/pull/30
not tested but seems mistakes
> fix: autoware_msgs

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
A mistake in converting `traffic_light_groups` message
> fix(perception replayer): fix a bug in converting old traffic light message.

- common/tier4_screen_capture_rviz_plugin/README.md
- common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.cpp
- common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.hpp
The code changes introduce new functions for capturing video with a buffer. 
This allows for capturing and saving video frames with a delay, enabling the user to save a specified number of frames in memory before writing them to a file.
I confirmed the following functionality:
1. **Start Recording**:
Executing the command below initiates the video recording:
```
ros2 service call /debug/capture/video_with_buffer std_srvs/srv/Trigger
```
2. **Save Buffered Video**:
When the same command is executed again, it saves a video starting from 10 seconds before the execution time.
This verification ensures that the system correctly implements a 10-second buffer for video capture, allowing users to save recent footage on demand.
The following video is saved starting from 10 seconds before the …
> feat(tier4_screen_capture_rviz_plugin): add video capture with buffer functionality

- evaluation/tier4_metrics_rviz_plugin/include/metrics_visualize_panel.hpp
Topic name change, see below for details.
[Comment by Sugahara-san](https://star4.slack.com/archives/C03QW0GU6P7/p1721704875996739?thread_ts=1721700599.221729&cid=C03QW0GU6P7
)
> feat(metrics_visualize): rename topic diagnostic->planning or perception

- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/node.py
- common/autoware_debug_tools/autoware_debug_tools/processing_time_visualizer/tree.py
Add Total Processing Time Tree 
```
⏰ Worst Case Execution Time ⏰
100.00% objectsCallback: total 62.10 [ms], avg. 62.10 [ms], run count: 1
├── 0.03% trafficSignalsCallback: total 0.02 [ms], avg. 0.02 [ms], run count: 1
├── 0.00% removeStaleTrafficLightInfo: total 0.00 [ms], avg. 0.00 [ms], run count: 1
├── 0.03% updateObjectData: total 0.02 [ms], avg. 0.00 [ms], run count: 19
├── 7.29% getCurrentLanelets: total 4.52 [ms], avg. 0.24 [ms], run count: 19
│   ├── 1.69% checkCloseLaneletCondition: total 1.05 [ms], avg. 0.01 [ms], run count: 190
│   ├── 0.00% isDuplicated: total 0.00 [ms], avg. 0.00 [ms], run count: 30
│   ├── 0.30% calculateLocalLikelihood: total 0.19 [ms], avg. 0.01 [ms], run count: 18
│   └── 5.30% rest: 3.29 [ms]
├── 0.36% updateRoadUsersHistory: total 0.23 [ms], avg. 0.01 …
```
> feat(autoware_debug_tools): processing time total processing tree

- control/control_debug_tools/scripts/lateral_deviation_monitor.py
print max value
https://github.com/user-attachments/assets/14ac8a48-6bb5-442b-8b6c-bb4f90071fb5
psim
> feat(control): print max value in lateral deviation monitor

- localization/deviation_estimation_tools/deviation_evaluator/launch/deviation_evaluator.launch.xml
Counterpart of https://github.com/autowarefoundation/autoware.universe/pull/8222
> chore: changed the package name imu_corrector to autoware_imu_corrector

- build_depends.repos
- planning/planning_debug_tools/package.xml
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
According to this [discussion](https://star4.slack.com/archives/C06TDLYKYBS/p1725855688653959), This PR removes the support for old rosbags with auto-msgs.
Note that perception_reproducer can not be used directly for old rosbag now. In the future, we may update this [tool](https://github.com/autowarefoundation/autoware_msg_bag_converter) to convert old rosbag for perception_reproducer.  
[pull request …
> chore: remove the support to auto-msgs.

- bag2lanelet/scripts/bag2map.py
- planning/autoware_planning_data_analyzer/config/behavior_analyzer.param.yaml
- planning/autoware_planning_data_analyzer/src/data_structs.cpp
- planning/autoware_planning_data_analyzer/src/data_structs.hpp
- planning/autoware_planning_data_analyzer/src/node.cpp
- planning/autoware_planning_data_analyzer/src/node.hpp
- improve performance of weight grid search
> perf(planning_data_analyzer): improve performance of weight grid search

- control_data_collecting_tool/CMakeLists.txt
- control_data_collecting_tool/README.md
- control_data_collecting_tool/config/param.yaml
- control_data_collecting_tool/launch/control_data_collecting_tool.launch.py
- control_data_collecting_tool/scripts/data_collecting_plotter.py
- control_data_collecting_tool/scripts/data_collecting_trajectory_publisher.py
I Improved `/data_collecting_trajectory_publisher` in the following two aspects.
- Added arrows
To make the direction of the vehicle's movement clearer, I added arrows in the tangential direction of the trajectory.
- Resolved the issue of the frequency becoming lower 
I resolved the issue of frequency drop by moving the code for visualizing the collected data to `/data_collecting_plotter`.
The average frequency became closer to the theoretical value of 33 Hz, and the maximum cycle time also decreased to around 0.080 seconds.
After all checkboxes are checked, anyone who has write …
> feat(control_data_collecting_tool): improve `/data_collecting_trajectory_publisher`

- .github/workflows/build-and-test-differential.yaml
- .github/workflows/cancel-previous-workflows.yaml
- .github/workflows/check-build-depends.yaml
- .github/workflows/clang-tidy-pr-comments-manually.yaml
- .github/workflows/clang-tidy-pr-comments.yaml
- .github/workflows/delete-closed-pr-docs.yaml
- .github/workflows/deploy-docs.yaml
- .github/workflows/github-release.yaml
- .github/workflows/json-schema-check.yaml
- .github/workflows/openai-pr-reviewer.yaml
- .github/workflows/pr-labeler.yaml
- .github/workflows/pre-commit-optional.yaml
- .github/workflows/pre-commit.yaml
- .github/workflows/spell-check-all.yaml
- .github/workflows/spell-check-partial.yaml
- .github/workflows/sync-files.yaml
- .github/workflows/update-codeowners-from-packages.yaml
This PR changes the runs-on value to ubuntu-22.04 instead of ubuntu-latest in github workflows.
https://github.com/autowarefoundation/autoware/pull/5320
Not applicable
Not applicable
None
None
> fix(.github): change runs-on value to to ubuntu-22.04

- control/control_debug_tools/scripts/lateral_deviation_monitor.py
no updates at high frequency to smooth the graph
before
after
psim
> feat(control_debug_tools): smooth graph lateral_deviation_monitor

- map/autoware_lanelet2_map_validator/package.xml
Add maintainers for the `autoware_lanelet2_map_validator`.
None
Not applicable
None
None
None
> chore(autoware_lanelet2_map_validator): add maintainers

- common/autoware_debug_tools/package.xml
Watanabe-san and I have been maintaining this tool recently, so this pull request will add us as maintainers.
None
None
None
None
> chore(autoware_debug_tools): add maintainers

- planning/autoware_planning_data_analyzer/launch/behavior_analyzer.launch.xml
https://github.com/autowarefoundation/autoware.universe/pull/9302
https://github.com/autowarefoundation/autoware/issues/5077
https://github.com/autowarefoundation/autoware/issues/4569
> refactor(glog_component): prefix package and namespace with autoware

- control/vehicle_cmd_analyzer/launch/vehicle_cmd_analyzer.launch.xml
- planning/autoware_planning_data_analyzer/launch/behavior_analyzer.launch.xml
- vehicle/parameter_estimator/launch/parameter_estimator.launch.xml
https://github.com/autowarefoundation/autoware.universe/pull/9303
https://github.com/autowarefoundation/autoware/issues/5077
https://github.com/autowarefoundation/autoware/issues/4569
> refactor(global_parameter_loader): prefix package and namespace with autoware

- .github/workflows/spell-check-all.yaml
- .github/workflows/spell-check-partial.yaml
currently @xmfcx made https://github.com/autowarefoundation/autoware-spell-check-dict. so autoware_tools should use this one.
this is part of https://github.com/autowarefoundation/autoware_tools/pull/11 but it needs time to solve conflict
> ci(spell-check): use awf dict

- .github/sync-files.yaml
- https://github.com/autowarefoundation/autoware/issues/4058
- https://github.com/autowarefoundation/autoware_tools/pull/11#issuecomment-2549656595
> ci(sync-files): utilize the sync-file-templates repository

- planning/autoware_static_centerline_generator/src/centerline_source/optimization_trajectory_based_centerline.cpp
Makes appropriate changes to support new changes made to autoware.core
None.
None.
> fix(autoware_static_centerline_generator): changes to support modifications made to autoware.core

- common/autoware_debug_tools/autoware_debug_tools/frequent_log_checker.py
hold the largest number of each frequent log and print it at last
None.
None.
> fix(frequent_log_checker): print the largest number of each frequent log

- build_depends.repos
- planning/autoware_static_centerline_generator/CMakeLists.txt
- planning/autoware_static_centerline_generator/config/static_centerline_generator.param.yaml
- planning/autoware_static_centerline_generator/package.xml
- planning/autoware_static_centerline_generator/rviz/static_centerline_generator.rviz
- planning/autoware_static_centerline_generator/src/centerline_source/optimization_trajectory_based_centerline.cpp
- planning/autoware_static_centerline_generator/src/centerline_source/optimization_trajectory_based_centerline.hpp
- planning/autoware_static_centerline_generator/src/static_centerline_generator_node.cpp
- planning/autoware_static_centerline_generator/src/utils.cpp
- 1. introduced glog 
- build_depends.repos is updated to clone tier4/glog.
- 2. added a visualization of the iterative path planning
- 3. fixed several bugs
- error handling when the centerline's size on the lanelet2 map is less than or equal to 2.
- added an orientation check in addition to the position check to handle the overlapped lanes
2 can show us the following iterative visualization
- yellow: smoothed trajectory
- blue: optimized trajectory
https://github.com/user-attachments/assets/e2b93f97-fbc5-49fa-9aaf-39c33c2d36ec
Unit test passed
None.
None.
> feat(static_centerline_generator): visualize iterative planning results and introduce glog

- planning/planning_debug_tools/scripts/trajectory_visualizer/README.md
- planning/planning_debug_tools/scripts/trajectory_visualizer/gui.py
- planning/planning_debug_tools/scripts/trajectory_visualizer/plotter.py
- planning/planning_debug_tools/scripts/trajectory_visualizer/ros2_interface.py
- planning/planning_debug_tools/scripts/trajectory_visualizer/trajectory_data.py
- planning/planning_debug_tools/scripts/trajectory_visualizer/visualizer.py
Add a script to easily visualize and compare Autoware trajectories for various metrics.
Visualized trajectories using Psim and rosbag replay.
None.
None.
> feat(planning_debug_tools): add trajectory visualizer tool

- system/rqt_diagnostic_graph_monitor/python/graph.py
- system/rqt_diagnostic_graph_monitor/python/widget.py
Reflect message change of diagnostic graph.
Check that the diagnostic graph is displayed using this tool with planning simulator.
`ros2 run rqt_diagnostic_graph_monitor rqt_diagnostic_graph_monitor`
None.
None.
> feat(rqt_diagnostic_graph_monitor): reflect diagnostic graph msg change

- localization/autoware_localization_evaluation_scripts/package.xml
This PR changes the maintainer of `autoware_localization_evaluation_scripts`.
None.
None.
> chore: change the maintainer of `autoware_localization_evaluation_scripts`

- common/tier4_debug_tools/launch/lateral_error_publisher.launch.xml
- planning/autoware_planning_data_analyzer/launch/behavior_analyzer.launch.xml
- planning/autoware_planning_data_analyzer/src/data_structs.cpp
- planning/planning_debug_tools/README.md
- planning/planning_debug_tools/launch/behavior_velocity_analyzer.launch.xml
- planning/planning_debug_tools/launch/trajectory_analyzer.launch.xml
- planning/planning_debug_tools/scripts/trajectory_visualizer.py
- planning/planning_debug_tools/scripts/trajectory_visualizer/config.yaml
This is the PR corresponding to phase 2. This PR is scheduled to be merged on August 11.
https://github.com/autowarefoundation/autoware/issues/6292
Please refer to this.
https://github.com/autowarefoundation/autoware/issues/6292#issuecomment-3166352528
None.
None.
> feat: change planning output topic name to /planning/trajectory

- planning/planning_debug_tools/scripts/trajectory_visualizer/gui.py
- planning/planning_debug_tools/scripts/trajectory_visualizer/plotter.py
- planning/planning_debug_tools/scripts/trajectory_visualizer/trajectory_data.py
This PR includes the following improvements to the trajectory visualizer's visualization:
- Set the aspect ratio to 1:1 for XY plots
- Add a preset that does not normalize the range for Yaw plots
None.
None.
> feat(planning_debug_tools): improve trajectory visualizer usability
